### ISSUE TITLE
Free stock music and sound effects?

### ISSUE THREAD

**Issue by nh916** [bradtraversy/design-resources-for-developers#134]
I was wondering if you knew a place for free stock music and free sound effects to use in a project. Big thanks!

**Comment by AssouaAlbert** [comment]
It will be great to add this set to the collection

**Comment by nh916** [comment]
I found these but not sure how good they are or if there is anything more popular

https://www.free-stock-music.com/
https://www.bensound.com/
https://mixkit.co/free-stock-music/
https://freesound.org/

**Comment by TheWizardBear** [comment]
https://freemusicarchive.org/

**Comment by bradtraversy** [comment]
Good Idea. I will create a category for free music
