### ISSUE TITLE
Duplicate Design Tools Link

### ISSUE THREAD

**Issue by MarkMoretto** [bradtraversy/design-resources-for-developers#135]
Under **Online Design Tools**, I think the link for "Colorsinspo" is listed twice.

(Great repo, BTW!  I'm not really a web developer, but make some apps on occasion.  This is one I've definitely bookmarked and will try to make a regular stop.)

**Comment by StefanSelfTaught** [comment]
Glad you like it! Thanks for the observation, will be fixed.
