### ISSUE TITLE
Why are PR being closed without feedback ?

### ISSUE THREAD

**Issue by ColinEspinas** [bradtraversy/design-resources-for-developers#139]
Hey, just wondered why PR are being closed, it has been said to resubmit them but even after that mine has been closed a second time, we are just trying to improve this resource for the community. 

Can you give more feedback when closing PRs ?

**Comment by Ademking** [comment]
same question

**Comment by bradtraversy** [comment]
Sorry, there was a flood of PRs and things were getting messy. Please refer to the contributing guidelines doc and resubmit. One resource per PR. Thanks
