### ISSUE TITLE
Proposal: Refer to a dedicated repository for JS frameworks

### ISSUE THREAD

**Issue by sunchayn** [bradtraversy/design-resources-for-developers#223]
The resource list will eventually grow to be kinda overwhelming to scan and get benefits from. To reduce that, I suggest we can simply refer to an **awesome-{framework}** for the given framework. Hence visitor could refer to that specific repository which most likely will have more curated content with more details.

Example: 

## Vue UI
>UI and component libraries for the Vue JavaScript framework

| Resource&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | Description |
| ----------------------- | ------------------ |
| [Awesome Vue](https://github.com/vuejs/awesome-vue#components--libraries)| A curated list of awesome things related to Vue.js |

**Comment by bradtraversy** [comment]
Not a bad idea. I'll put some thought into it. I can see this getting way too large lol. Thanks for the feedback
