### ISSUE TITLE
Multiple Resources

### ISSUE THREAD

**Issue by dridge737** [bradtraversy/design-resources-for-developers#277]
Where can I place website with multiple resources available? I saw this website
| [Graphic Burger](https://graphicburger.com/) | A website that offers a collection of free Mockups, Ui Kits, Icons, Text Effect and Background. |

**Comment by StanSkrivanek** [comment]
I have two IMHO useful sites as well but I don't want to contribute. If someone will add these into this list it will be great, if not It's ok as I have them in bookmarks anyway.

https://www.designvalley.club
https://www.lapa.ninja

**Comment by Alaev** [comment]
Hey @dridge737, Thanks for the question.

I would say it can go in `UI Components & Kits` or `Inspiration section`.
What do you think?

**Comment by dridge737** [comment]
Oh alright. will change the area haha
