### ISSUE TITLE
Not free ressources in the list

### ISSUE THREAD

**Issue by Kafiil** [bradtraversy/design-resources-for-developers#318]
Hello,
I found out that there are some paid ressources ( ex: kendo react ui), I thought this was free only.

If you ever need help with validating and checking the ressources before merging the PR I could volunteer.

Thanks again for the awesome list 👍

**Comment by StefanSelfTaught** [comment]
Thank you for your observation 😄. Unfortunately Brad missed that. However, now we are accepting only one resource per PR and it's easier to check it. I try to check all the resources in depth before PR.

**Comment by Kafiil** [comment]
OK 👍 
Anyway, let me know if you ever need someone to help.
And keep up the good work 💯
