### ISSUE TITLE
Should there a category of developer to follow as well?

### ISSUE THREAD

**Issue by rattanakchea** [bradtraversy/design-resources-for-developers#342]
Just curious if people category is suitable for this? Or even blogs, or youtube since they also provide valuable information. Thanks

**Comment by LeonnardoVerol** [comment]
Like This?

https://github.com/bradtraversy/DevYouTubeList

**Comment by TechLead-21** [comment]
Thanks for your suggestion @rattanakchea, I think it's not a good idea. We should stick with our main motive for this repo.
Btw, Brad has a dedicated repo as you mentioned.

**Comment by StefanSelfTaught** [comment]
I agree to @TechLead-21, this repo is about design and related things. Thanks for suggestion.
