### ISSUE TITLE
Proposal: Dedicated section for FavIcons Resource

### ISSUE THREAD

**Issue by LeonnardoVerol** [bradtraversy/design-resources-for-developers#344]
Currently, there are 3 favicons resources inside "Online Design Tools".

Since they are pretty specific and also a generator (2 of them), it should make sense to move them to a new dedicated section that's easier to look for.

Also, when building web apps/sites, favicons are sufficiently important enough that you need to give some more attention.

**Comment by StefanSelfTaught** [comment]
Good idea! Will be added.
