### ISSUE TITLE
editors pick or top picks?

### ISSUE THREAD

**Issue by nh916** [bradtraversy/design-resources-for-developers#423]
I thought since there is a lot of great resources here something like adding most recommended link in each category would be great to not have information overload or more categorization so there is only a few things in each category.

**Comment by Alaev** [comment]
That is a Good thought. we need to think about the ranking system. how do you give score to each resource?

**Comment by nh916** [comment]
maybe a vote?

it could be based on 
ease of set up
ease of understanding
popularity
support availability
enjoyability of using it

and each category awards it some points and the one with most points is the people's choice
what you think?

**Comment by bradtraversy** [comment]
I am ok with that, but some categories have resources that are wildly different than the others and used for different purposes so it may be difficult. When I created this I basically put my favorite resources first in each category, but I can vote if needed. It's up to you guys, I didn't even expect it to get this big lol

**Comment by bradtraversy** [comment]
I think we'll put this on hold for now
