### ISSUE TITLE
Wrong link of Promo Image Resizer website

### ISSUE THREAD

**Issue by romitrajsahu** [bradtraversy/design-resources-for-developers#426]
Hello Guys,

The link that has been provided for Promo Image Resizer website is incorrect. You have provided the link to CompressNow website. Please change the link to https://promo.com/tools/image-resizer/ 

I am a NewBie to GitHub and this is my First Ever Issue. So, if I had done something wrong then please tell me.

**Comment by StefanSelfTaught** [comment]
Thank you for your observation, will be fixed 👍
