### ISSUE TITLE
Should we include WordPress in this resource list?

### ISSUE THREAD

**Issue by jeanluc243** [bradtraversy/design-resources-for-developers#427]
I wanted to know your thoughts on this. If you're ok with it, You can start adding **WordPress-related UI resources** to this list too.

**Comment by Alaev** [comment]
Hey,
Do you have an example? elementor etc... I think they are not `design` related materials and WP list can take a huge portion.

**Comment by jeanluc243** [comment]
I would also say it would be better to make a **list of the best sites** where we can find paid or Free **Wordpress Templates**.

Sites where we can find plugins or similar sites.

**Comment by bradtraversy** [comment]
I think Wordpress theme sites can go under templates, etc. I don't think plugins and stuff like that really fit anywhere

**Comment by Semirxbih** [comment]
I'd love this!
