### ISSUE TITLE
Add a license(s) section

### ISSUE THREAD

**Issue by JoaoMarquesFidalgo** [bradtraversy/design-resources-for-developers#447]
Hi, I was making a simple website and came across a list of several things to do, one of which was adding a license to your project. I don't know if it's useful to the theme of the repository, but I believe to be important for newer programmers such as myself.

The resource I used for an open-source license was: https://choosealicense.com/

Thanks for reading and to Brad for making this repo, be safe.

**Comment by Alaev** [comment]
Hey @JoaoMarquesFidalgo ,

First of all, This repo is under `MIT` that said not all the resources here follows the same license.
as a developer/designer you should be able to pick the resources that best suit your needs in the best possible way.

Some people are fine with giving credit as alike others will search for MIT/

Regards,
Mike.
