### ISSUE TITLE
Req: Adding backend stuff?

### ISSUE THREAD

**Issue by maotora** [bradtraversy/design-resources-for-developers#450]
Hi,

I have a request if you can add some Nodejs back-end stuff too like;

- Authentication modules/solutions

- ORMs 

- Frameworks & Libraries etc..

PS: Thank you for this repo man it has saved us tons of searches. 🍻

**Comment by Alaev** [comment]
I think it's not 100% design related. as you will have to cover a handful of backend languages... (js, .net, ruby, PHP, Elixer, etc...)
