### ISSUE TITLE
Can you add this one?

### ISSUE THREAD

**Issue by ElchananBS** [bradtraversy/design-resources-for-developers#456]
[https://silhouette-ac.com/](https://silhouette-ac.com/)
Hey Brad, thank you sincerely for all of your great content including this great repository.
Here is a site I get across when working on a project, which offers a great amount of high quality **free**  silhouettes.
(They delay each download for 15 sec and credits the creator in a meta data)

**Comment by Alaev** [comment]
Hey @ElchananBS,
Feel free to submit a PR with the resource. however, I think you can find plenty of recourse that have the same high-quality illustrations
