### ISSUE TITLE
Browsers for testing Designs?

### ISSUE THREAD

**Issue by warwickofthegh** [bradtraversy/design-resources-for-developers#484]
Would alternate browsers used for design testing be useful on this list? 

example alternate browsers such as **Blisk**, **Sizzy**(though paid but for example)

Love the list and thanks to all who have contributed!!

**Comment by sw-yx** [comment]
i like Sizzy!

**Comment by Alaev** [comment]
I would recommend using https://github.com/manojVivek/responsively-app
However, if you like you can create a list for browsers for testing.
