### ISSUE TITLE
Should we include Gatsby in this resource list?

### ISSUE THREAD

**Issue by virajkulkarni14** [bradtraversy/design-resources-for-developers#73]
First of all, thank you so much @bradtraversy for creating this really handy resource!

I wanted to ask if adding a section related to Gatsby to this list of resources would be apt?

While we have list of resources of UI libs for React, Vue & Angular, I'm not sure if Gatsby too belongs to the same category or not. Gatsby has come a long way from being just a static site generator to a full blown React-based framework.

I wanted to know your thoughts on this. If you're ok with it, I will start adding Gatsby-related UI resources to this list too.

Thank you & with regards,
Viraj

**Comment by gualterandre** [comment]
I second this. It makes sense to me as well

**Comment by bradtraversy** [comment]
Sure, I guess we could do that. It makes sense. Feel free to make a pr
