### ISSUE TITLE
Where should I put React Native UI Framework?

### ISSUE THREAD

**Issue by richardoey** [bradtraversy/design-resources-for-developers#773]
I found this [Magnus UI - React Native UI Framework](https://magnus-ui.com/). 

Magnus UI is the ultimate UI framework that helps you in building consistent user interfaces effortlessly in react native.

Link: https://magnus-ui.com/

Should I put it inside the React UI section? sorry if I mention this in the Issues.

**Comment by Alaev** [comment]
Hey, can You can create new react native section and put it there?

**Comment by richardoey** [comment]
Yeah, with pleasure ! Thank you for the permission 💪
