### ISSUE TITLE
How to add icon to an existing resource?

### ISSUE THREAD

**Issue by idoshamun** [bradtraversy/design-resources-for-developers#784]
First of all thanks for featuring daily.dev! 🙏
I would love to update the default logo you show on the website to our actual logo.
What would be the best you to contribute?
![image](https://user-images.githubusercontent.com/1993245/111273872-0205e580-863d-11eb-91d3-503631472e48.png)

**Comment by Alaev** [comment]
@idoshamun Hey Ido,
This list is a markdown file can you elaborate more with your issue? "default logo you show on the website to our actual logo."

**Comment by idoshamun** [comment]
@Alaev thanks for the quick response.
I was thinking this repo holds the database for this site:
https://designresources.dev/

My extension daily.dev is shown here:
https://designresources.dev/chrome-extensions/
with a default Google logo. I would like to change it, if possible of course.

**Comment by Alaev** [comment]
Nope, I think he(https://twitter.com/csaba_kissi) created the website from this list. try sending him a DM.
