### ISSUE TITLE
Hey! I did not find any links for the background waves.

### ISSUE THREAD

**Issue by Anoopkumarseth** [bradtraversy/design-resources-for-developers#893]
Here is some background waves sites please add 

https://www.shapedivider.app/
https://svgwave.in/
https://loading.io/background/m-wave/
https://makebackground.io/
https://getwaves.io/
https://wweb.dev/resources/css-separator-generator
https://wavelry.vercel.app/

**Comment by Alaev** [comment]
Hey, Thanks for the issue!

There are only two missing assets, however we have other resource in the list that do same functionality with better features. better :)

![image](https://user-images.githubusercontent.com/3925474/124788521-16eee780-df52-11eb-9652-864f3dfaa5bd.png)
![image](https://user-images.githubusercontent.com/3925474/124788610-2cfca800-df52-11eb-8256-df65a0e6c44c.png)
![image](https://user-images.githubusercontent.com/3925474/124788664-3ab22d80-df52-11eb-8de1-3273a1904f24.png)

etc...

Closing.
