### ISSUE TITLE
A website for this repo 

### ISSUE THREAD

**Issue by rohan220217** [bradtraversy/design-resources-for-developers#905]
Hey Brad, 
I love your videos and I am following this repo from the very start when you uploaded it. But I think a website for this repo is need of the hour like every section and its link can be view in HTML or we can add a gif for every link. 
What's your opinion about this?

**Comment by Alaev** [comment]
if you want you can create a git hub pages PR :)

**Comment by rohan220217** [comment]
sure I would love to do so 🤗
